micronaut:
  application:
    name: pisBackend
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret:
                '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThissecretForANewOne}"'
  server:
    port: 8000
    
netty:
  default:
    allocator:
      max-order: 3
